name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution to this Repository. 🚀🚀🚀 Your issue will be sorted as soon as our moderator [Priyanshu](https://github.com/kumarsonsoff3) will back online.'
        pr-message: 'Thanks for your contribution to this Project.  Your contribution will shortly be Reviewed 🚀🚀🚀'
